#!/bin/sh
#/etc/init.d/hoodservice
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/lib/node_modules

case "$1" in
start)
echo "starting hoodrelay.js"
exec forever --sourceDir=/usr/local/bin/server -p /usr/local/bin/server hoodrelay.js  #scriptarguments
;;
stop)
echo "stopping hoodrelay.js"
exec forever stop --sourceDir=/usr/local/bin/server hoodrelay.js
;;
*)
echo "Usage: /etc/init.d/hoodservice {start|stop}"
exit 1
;;
esac
exit 0